alter table public.recipes drop column if exists preparation;

create table if not exists public.recipe_instructions (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  step_number integer not null check (step_number >= 1),
  text text not null
);

alter table public.recipe_instructions enable row level security;

create policy "Anyone can read recipe instructions"
  on public.recipe_instructions for select
  using (true);

insert into public.recipe_instructions (recipe_id, step_number, text)
select r.id, v.step_number, v.text
from (values
  ('Porridge avoine-banane', 1, 'Fais chauffer le lait dans une casserole.'),
  ('Porridge avoine-banane', 2, 'Ajoute les flocons d''avoine et laisse mijoter à feu doux pendant 5 minutes en remuant régulièrement.'),
  ('Porridge avoine-banane', 3, 'Écrase la banane et incorpore-la en fin de cuisson, puis sers chaud.'),
  ('Œufs brouillés et pain complet', 1, 'Bats les œufs dans un bol avec une pincée de sel.'),
  ('Œufs brouillés et pain complet', 2, 'Fais-les cuire à feu doux dans une poêle beurrée en remuant constamment jusqu''à obtenir une texture crémeuse.'),
  ('Œufs brouillés et pain complet', 3, 'Sers avec les tranches de pain complet légèrement toastées.'),
  ('Yaourt grec, granola et fruits rouges', 1, 'Verse le yaourt grec dans un bol.'),
  ('Yaourt grec, granola et fruits rouges', 2, 'Ajoute le granola par-dessus pour garder son croquant.'),
  ('Yaourt grec, granola et fruits rouges', 3, 'Termine avec les fruits rouges frais ou décongelés.'),
  ('Pancakes protéinés', 1, 'Mélange la farine, les œufs et la whey protéine jusqu''à obtenir une pâte homogène sans grumeaux.'),
  ('Pancakes protéinés', 2, 'Fais chauffer une poêle légèrement huilée à feu moyen.'),
  ('Pancakes protéinés', 3, 'Verse des petites louches de pâte et fais cuire 2 minutes de chaque côté jusqu''à ce que des bulles apparaissent en surface.'),
  ('Poulet grillé, riz et brocolis', 1, 'Fais cuire le riz selon les instructions du paquet.'),
  ('Poulet grillé, riz et brocolis', 2, 'Grille le blanc de poulet à la poêle ou au grill 5-6 minutes de chaque côté.'),
  ('Poulet grillé, riz et brocolis', 3, 'Fais cuire les brocolis à la vapeur 8 minutes.'),
  ('Poulet grillé, riz et brocolis', 4, 'Assemble le tout dans une assiette.'),
  ('Saumon, quinoa et légumes vapeur', 1, 'Rince le quinoa puis fais-le cuire dans deux fois son volume d''eau pendant environ 15 minutes.'),
  ('Saumon, quinoa et légumes vapeur', 2, 'Cuis le pavé de saumon à la poêle ou au four 12-15 minutes.'),
  ('Saumon, quinoa et légumes vapeur', 3, 'Fais cuire les légumes à la vapeur en parallèle.'),
  ('Wrap dinde-avocat', 1, 'Écrase l''avocat à la fourchette et tartine-le sur la tortilla.'),
  ('Wrap dinde-avocat', 2, 'Ajoute les tranches de dinde par-dessus.'),
  ('Wrap dinde-avocat', 3, 'Roule fermement le wrap et coupe-le en deux.'),
  ('Buddha bowl pois chiches', 1, 'Fais cuire le riz selon les instructions du paquet.'),
  ('Buddha bowl pois chiches', 2, 'Rince les pois chiches et fais-les revenir quelques minutes à la poêle avec les épinards jusqu''à ce qu''ils soient tendres.'),
  ('Buddha bowl pois chiches', 3, 'Dresse le tout dans un bol.'),
  ('Steak haché, patate douce et haricots verts', 1, 'Coupe la patate douce en cubes et fais-la rôtir au four 25 minutes à 200°C.'),
  ('Steak haché, patate douce et haricots verts', 2, 'Fais cuire les haricots verts à la vapeur.'),
  ('Steak haché, patate douce et haricots verts', 3, 'Saisis le steak haché à la poêle 3-4 minutes de chaque côté selon la cuisson désirée.'),
  ('Pâtes bolognaise (bœuf 5%)', 1, 'Fais cuire les pâtes dans l''eau bouillante salée selon les instructions du paquet.'),
  ('Pâtes bolognaise (bœuf 5%)', 2, 'Fais revenir le bœuf haché dans une poêle jusqu''à ce qu''il soit doré.'),
  ('Pâtes bolognaise (bœuf 5%)', 3, 'Ajoute la sauce tomate et laisse mijoter 10 minutes.'),
  ('Pâtes bolognaise (bœuf 5%)', 4, 'Mélange aux pâtes égouttées.'),
  ('Cabillaud, riz basmati et courgettes', 1, 'Fais cuire le riz basmati selon les instructions du paquet.'),
  ('Cabillaud, riz basmati et courgettes', 2, 'Fais cuire le cabillaud à la vapeur ou au four 12 minutes.'),
  ('Cabillaud, riz basmati et courgettes', 3, 'Fais revenir les courgettes coupées en rondelles à la poêle avec un filet d''huile d''olive.'),
  ('Tofu sauté, nouilles et légumes', 1, 'Fais cuire les nouilles selon les instructions du paquet.'),
  ('Tofu sauté, nouilles et légumes', 2, 'Coupe le tofu en cubes et fais-le dorer à la poêle avec un peu d''huile.'),
  ('Tofu sauté, nouilles et légumes', 3, 'Ajoute les légumes sautés et mélange le tout avec les nouilles égouttées.'),
  ('Barre protéinée maison', 1, 'Mélange les flocons d''avoine avec la whey protéine et un peu d''eau ou de lait jusqu''à obtenir une pâte compacte.'),
  ('Barre protéinée maison', 2, 'Étale-la sur une plaque et tasse bien.'),
  ('Barre protéinée maison', 3, 'Réfrigère au moins 1 heure avant de découper en barres.'),
  ('Pomme et beurre de cacahuète', 1, 'Coupe la pomme en quartiers.'),
  ('Pomme et beurre de cacahuète', 2, 'Sers-la accompagnée du beurre de cacahuète pour tremper.'),
  ('Fromage blanc et miel', 1, 'Verse le fromage blanc dans un bol.'),
  ('Fromage blanc et miel', 2, 'Arrose-le d''un filet de miel juste avant de servir.'),
  ('Muesli maison et lait d''amande', 1, 'Verse le muesli dans un bol.'),
  ('Muesli maison et lait d''amande', 2, 'Ajoute le lait d''amande froid par-dessus juste avant de servir pour garder le croquant.'),
  ('Omelette au fromage et jambon', 1, 'Bats les œufs dans un bol avec une pincée de sel.'),
  ('Omelette au fromage et jambon', 2, 'Fais chauffer une poêle beurrée et verse les œufs.'),
  ('Omelette au fromage et jambon', 3, 'Ajoute le jambon coupé en dés et le fromage râpé.'),
  ('Omelette au fromage et jambon', 4, 'Replie l''omelette en deux une fois prise.'),
  ('Smoothie bowl banane-myrtille', 1, 'Mixe la banane, les myrtilles et le yaourt grec ensemble jusqu''à obtenir une texture épaisse et lisse.'),
  ('Smoothie bowl banane-myrtille', 2, 'Verse dans un bol et ajoute des toppings de ton choix si tu veux.'),
  ('Toast à l''avocat et œuf poché', 1, 'Fais toaster le pain complet.'),
  ('Toast à l''avocat et œuf poché', 2, 'Poche les œufs dans une casserole d''eau frémissante additionnée d''un peu de vinaigre pendant 3 minutes.'),
  ('Toast à l''avocat et œuf poché', 3, 'Écrase l''avocat sur le pain toasté et dépose l''œuf poché par-dessus.'),
  ('Crêpes à la farine complète et miel', 1, 'Mélange la farine complète avec les œufs et un peu de lait pour obtenir une pâte à crêpe fluide.'),
  ('Crêpes à la farine complète et miel', 2, 'Fais cuire les crêpes dans une poêle chaude légèrement huilée.'),
  ('Crêpes à la farine complète et miel', 3, 'Arrose de miel avant de servir.'),
  ('Bagel au saumon fumé et fromage frais', 1, 'Coupe le bagel en deux et fais-le légèrement toaster.'),
  ('Bagel au saumon fumé et fromage frais', 2, 'Tartine de fromage frais.'),
  ('Bagel au saumon fumé et fromage frais', 3, 'Ajoute les tranches de saumon fumé par-dessus.'),
  ('Porridge protéiné chocolat-noisette', 1, 'Fais chauffer le lait dans une casserole.'),
  ('Porridge protéiné chocolat-noisette', 2, 'Ajoute les flocons d''avoine et laisse mijoter à feu doux 5 minutes.'),
  ('Porridge protéiné chocolat-noisette', 3, 'Incorpore la whey protéine hors du feu en remuant bien pour éviter les grumeaux.'),
  ('Gaufres maison et fruits', 1, 'Mélange la farine avec les œufs et un peu de lait pour former une pâte à gaufre.'),
  ('Gaufres maison et fruits', 2, 'Fais cuire dans un gaufrier chaud quelques minutes jusqu''à ce qu''elles soient dorées.'),
  ('Gaufres maison et fruits', 3, 'Sers avec les fruits rouges.'),
  ('Skyr et flocons d''avoine', 1, 'Verse le skyr dans un bol.'),
  ('Skyr et flocons d''avoine', 2, 'Ajoute les flocons d''avoine.'),
  ('Skyr et flocons d''avoine', 3, 'Arrose d''un filet de miel avant de servir.'),
  ('Sandwich œufs-bacon', 1, 'Fais cuire le bacon à la poêle jusqu''à ce qu''il soit croustillant.'),
  ('Sandwich œufs-bacon', 2, 'Fais cuire les œufs au plat ou brouillés.'),
  ('Sandwich œufs-bacon', 3, 'Assemble le tout entre les tranches de pain complet.'),
  ('Salade César au poulet', 1, 'Grille le blanc de poulet à la poêle 5-6 minutes de chaque côté puis coupe-le en lamelles.'),
  ('Salade César au poulet', 2, 'Mélange la salade romaine avec le parmesan râpé.'),
  ('Salade César au poulet', 3, 'Dispose le poulet par-dessus.'),
  ('Riz sauté au tofu et légumes', 1, 'Fais cuire le riz selon les instructions du paquet puis laisse-le refroidir si possible.'),
  ('Riz sauté au tofu et légumes', 2, 'Fais dorer le tofu coupé en cubes à la poêle.'),
  ('Riz sauté au tofu et légumes', 3, 'Ajoute les légumes sautés et le riz, et fais sauter le tout à feu vif quelques minutes.'),
  ('Poke bowl saumon-avocat', 1, 'Fais cuire le riz selon les instructions du paquet et laisse-le tiédir.'),
  ('Poke bowl saumon-avocat', 2, 'Coupe le saumon en cubes et tranche l''avocat.'),
  ('Poke bowl saumon-avocat', 3, 'Dresse le tout sur le riz.'),
  ('Sandwich club poulet-bacon', 1, 'Fais cuire le bacon à la poêle jusqu''à ce qu''il soit croustillant.'),
  ('Sandwich club poulet-bacon', 2, 'Grille le blanc de poulet.'),
  ('Sandwich club poulet-bacon', 3, 'Assemble entre les tranches de pain complet en superposant poulet et bacon.'),
  ('Pâtes au thon et tomates', 1, 'Fais cuire les pâtes dans l''eau bouillante salée selon les instructions du paquet.'),
  ('Pâtes au thon et tomates', 2, 'Fais chauffer la sauce tomate dans une poêle.'),
  ('Pâtes au thon et tomates', 3, 'Émiette le thon égoutté et mélange le tout aux pâtes égouttées.'),
  ('Curry de poulet et riz basmati', 1, 'Fais cuire le riz basmati selon les instructions du paquet.'),
  ('Curry de poulet et riz basmati', 2, 'Fais dorer le blanc de poulet coupé en morceaux dans une poêle.'),
  ('Curry de poulet et riz basmati', 3, 'Ajoute le lait de coco et laisse mijoter 10 minutes à feu doux.'),
  ('Salade de lentilles et feta', 1, 'Fais cuire les lentilles selon les instructions du paquet puis laisse-les refroidir.'),
  ('Salade de lentilles et feta', 2, 'Mélange-les avec les légumes coupés en dés.'),
  ('Salade de lentilles et feta', 3, 'Émiette la feta par-dessus.'),
  ('Burrito bœuf-haricots rouges', 1, 'Fais revenir le bœuf haché à la poêle jusqu''à ce qu''il soit doré.'),
  ('Burrito bœuf-haricots rouges', 2, 'Ajoute les haricots rouges égouttés et laisse chauffer quelques minutes.'),
  ('Burrito bœuf-haricots rouges', 3, 'Garnis la tortilla et roule fermement le burrito.'),
  ('Bol de quinoa aux crevettes', 1, 'Rince le quinoa et fais-le cuire dans deux fois son volume d''eau environ 15 minutes.'),
  ('Bol de quinoa aux crevettes', 2, 'Fais sauter les crevettes à la poêle 3-4 minutes jusqu''à ce qu''elles soient roses.'),
  ('Bol de quinoa aux crevettes', 3, 'Dresse le tout avec les légumes vapeur.'),
  ('Sandwich thon-crudités', 1, 'Égoutte le thon et mélange-le avec les crudités coupées en petits morceaux.'),
  ('Sandwich thon-crudités', 2, 'Garnis les tranches de pain complet avec ce mélange.'),
  ('Poulet rôti et pommes de terre', 1, 'Fais rôtir la cuisse de poulet au four à 200°C pendant 35-40 minutes jusqu''à ce que la peau soit dorée.'),
  ('Poulet rôti et pommes de terre', 2, 'Fais cuire les pommes de terre coupées en morceaux au four en même temps.'),
  ('Poulet rôti et pommes de terre', 3, 'Fais cuire les haricots verts à la vapeur.'),
  ('Chili con carne et riz', 1, 'Fais cuire le riz selon les instructions du paquet.'),
  ('Chili con carne et riz', 2, 'Fais revenir le bœuf haché à la poêle jusqu''à ce qu''il soit doré.'),
  ('Chili con carne et riz', 3, 'Ajoute les haricots rouges égouttés et laisse mijoter 15 minutes à feu doux.'),
  ('Gratin de saumon et brocolis', 1, 'Fais cuire les brocolis à la vapeur quelques minutes.'),
  ('Gratin de saumon et brocolis', 2, 'Dispose le saumon et les brocolis dans un plat à gratin, nappe de crème légère.'),
  ('Gratin de saumon et brocolis', 3, 'Fais cuire au four à 200°C pendant 20 minutes.'),
  ('Escalope de dinde et purée', 1, 'Fais cuire l''escalope de dinde à la poêle 4-5 minutes de chaque côté.'),
  ('Escalope de dinde et purée', 2, 'Fais bouillir les pommes de terre jusqu''à ce qu''elles soient tendres.'),
  ('Escalope de dinde et purée', 3, 'Écrase-les avec le beurre pour former une purée.'),
  ('Risotto aux champignons et parmesan', 1, 'Fais revenir le riz arborio dans une poêle.'),
  ('Risotto aux champignons et parmesan', 2, 'Ajoute progressivement du bouillon chaud en remuant régulièrement jusqu''à absorption complète, environ 18 minutes.'),
  ('Risotto aux champignons et parmesan', 3, 'Incorpore les champignons poêlés et le parmesan râpé en fin de cuisson.'),
  ('Curry de crevettes et riz', 1, 'Fais cuire le riz selon les instructions du paquet.'),
  ('Curry de crevettes et riz', 2, 'Fais sauter les crevettes à la poêle 2-3 minutes.'),
  ('Curry de crevettes et riz', 3, 'Ajoute le lait de coco et laisse mijoter 5 minutes à feu doux.'),
  ('Poêlée de bœuf et légumes asiatiques', 1, 'Fais chauffer un filet d''huile dans un wok ou une grande poêle.'),
  ('Poêlée de bœuf et légumes asiatiques', 2, 'Fais saisir le bœuf émincé à feu vif quelques minutes.'),
  ('Poêlée de bœuf et légumes asiatiques', 3, 'Ajoute les légumes sautés et la sauce soja, puis mélange bien avant de servir.'),
  ('Lasagnes à la viande', 1, 'Fais revenir le bœuf haché à la poêle avec la sauce tomate pendant 10 minutes.'),
  ('Lasagnes à la viande', 2, 'Monte les lasagnes en alternant plaques de pâtes et sauce à la viande.'),
  ('Lasagnes à la viande', 3, 'Fais cuire au four à 200°C pendant 30 minutes.'),
  ('Filet de poisson blanc et légumes rôtis', 1, 'Coupe les légumes et fais-les rôtir au four à 200°C avec un filet d''huile d''olive pendant 20 minutes.'),
  ('Filet de poisson blanc et légumes rôtis', 2, 'Fais cuire le filet de poisson blanc à la poêle ou au four 10-12 minutes.'),
  ('Chili végétarien et riz complet', 1, 'Fais cuire le riz complet selon les instructions du paquet.'),
  ('Chili végétarien et riz complet', 2, 'Fais chauffer les haricots rouges égouttés avec la sauce tomate dans une casserole.'),
  ('Chili végétarien et riz complet', 3, 'Laisse mijoter 15 minutes à feu doux.'),
  ('Amandes et fruits secs', 1, 'Mélange les amandes et les fruits secs dans un petit bol, prêt à emporter.'),
  ('Smoothie protéiné banane', 1, 'Mixe la banane, le lait et la whey protéine ensemble jusqu''à obtenir une texture lisse et mousseuse.'),
  ('Houmous et bâtonnets de légumes', 1, 'Coupe les carottes et le concombre en bâtonnets.'),
  ('Houmous et bâtonnets de légumes', 2, 'Sers-les accompagnés du houmous pour tremper.'),
  ('Yaourt et granola', 1, 'Verse le yaourt grec dans un bol.'),
  ('Yaourt et granola', 2, 'Ajoute le granola par-dessus juste avant de servir pour garder son croquant.'),
  ('Barre de céréales maison', 1, 'Mélange les flocons d''avoine avec le miel et les fruits secs jusqu''à obtenir une pâte collante.'),
  ('Barre de céréales maison', 2, 'Étale sur une plaque et tasse bien.'),
  ('Barre de céréales maison', 3, 'Réfrigère au moins 1 heure avant de découper en barres.'),
  ('Fromage cottage et fruits rouges', 1, 'Verse le fromage cottage dans un bol.'),
  ('Fromage cottage et fruits rouges', 2, 'Ajoute les fruits rouges frais ou décongelés par-dessus.'),
  ('Toast au beurre de cacahuète et banane', 1, 'Fais toaster la tranche de pain complet.'),
  ('Toast au beurre de cacahuète et banane', 2, 'Tartine de beurre de cacahuète.'),
  ('Toast au beurre de cacahuète et banane', 3, 'Dispose les rondelles de banane par-dessus.'),
  ('Œuf dur et fruit', 1, 'Fais cuire les œufs dans l''eau bouillante pendant 9-10 minutes.'),
  ('Œuf dur et fruit', 2, 'Passe-les sous l''eau froide avant de les écaler.'),
  ('Œuf dur et fruit', 3, 'Sers accompagnés de la pomme.'),
  ('Shake protéiné chocolat', 1, 'Mixe la whey protéine avec le lait jusqu''à obtenir une texture lisse et mousseuse.'),
  ('Shake protéiné chocolat', 2, 'Sers immédiatement.')
) as v(name, step_number, text)
join public.recipes r on r.name = v.name;
