-- Adds a prep-time field and a many-to-many category/protein tag system to
-- recipes, needed for the recipe browser screen's filters. The tag
-- vocabulary (poulet, boeuf, porc, dinde, poisson_fruits_de_mer, oeuf,
-- vegetarien) is fixed and enforced at the application layer, not by a
-- database check constraint.

alter table public.recipes
  add column prep_time_minutes integer null;

create table if not exists public.recipe_tags (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  tag text not null
);

alter table public.recipe_tags enable row level security;

create policy "Anyone can read recipe tags"
  on public.recipe_tags for select
  using (true);

-- Backfill prep_time_minutes for the 86 existing recipes.
update public.recipes r
set prep_time_minutes = v.minutes
from (values
  ('Porridge avoine-banane', 10),
  ('Œufs brouillés et pain complet', 10),
  ('Yaourt grec, granola et fruits rouges', 5),
  ('Pancakes protéinés', 15),
  ('Poulet grillé, riz et brocolis', 25),
  ('Saumon, quinoa et légumes vapeur', 25),
  ('Wrap dinde-avocat', 10),
  ('Buddha bowl pois chiches', 20),
  ('Steak haché, patate douce et haricots verts', 30),
  ('Pâtes bolognaise (bœuf 5%)', 30),
  ('Cabillaud, riz basmati et courgettes', 25),
  ('Tofu sauté, nouilles et légumes', 20),
  ('Barre protéinée maison', 10),
  ('Pomme et beurre de cacahuète', 5),
  ('Fromage blanc et miel', 5),
  ('Muesli maison et lait d''amande', 5),
  ('Omelette au fromage et jambon', 10),
  ('Smoothie bowl banane-myrtille', 10),
  ('Toast à l''avocat et œuf poché', 15),
  ('Crêpes à la farine complète et miel', 20),
  ('Bagel au saumon fumé et fromage frais', 10),
  ('Porridge protéiné chocolat-noisette', 10),
  ('Gaufres maison et fruits', 20),
  ('Skyr et flocons d''avoine', 5),
  ('Sandwich œufs-bacon', 15),
  ('Salade César au poulet', 20),
  ('Riz sauté au tofu et légumes', 20),
  ('Poke bowl saumon-avocat', 15),
  ('Sandwich club poulet-bacon', 15),
  ('Pâtes au thon et tomates', 20),
  ('Curry de poulet et riz basmati', 30),
  ('Salade de lentilles et feta', 15),
  ('Burrito bœuf-haricots rouges', 25),
  ('Bol de quinoa aux crevettes', 20),
  ('Sandwich thon-crudités', 10),
  ('Poulet rôti et pommes de terre', 45),
  ('Chili con carne et riz', 35),
  ('Gratin de saumon et brocolis', 35),
  ('Escalope de dinde et purée', 30),
  ('Risotto aux champignons et parmesan', 35),
  ('Curry de crevettes et riz', 25),
  ('Poêlée de bœuf et légumes asiatiques', 20),
  ('Lasagnes à la viande', 45),
  ('Filet de poisson blanc et légumes rôtis', 30),
  ('Chili végétarien et riz complet', 30),
  ('Amandes et fruits secs', 2),
  ('Smoothie protéiné banane', 5),
  ('Houmous et bâtonnets de légumes', 5),
  ('Yaourt et granola', 5),
  ('Barre de céréales maison', 10),
  ('Fromage cottage et fruits rouges', 5),
  ('Toast au beurre de cacahuète et banane', 5),
  ('Œuf dur et fruit', 12),
  ('Shake protéiné chocolat', 5),
  ('Gnocchis poêlés, chorizo & tomates cerises', 20),
  ('Tartare de saumon avocat-mangue', 15),
  ('Crevettes ail-persil-piment, tagliatelles citronnées', 20),
  ('Cabillaud rôti, sauce vierge & écrasé de patate douce', 25),
  ('Bowl bœuf teriyaki express', 15),
  ('Salade thaï poulet-cacahuète', 15),
  ('Saumon laqué miso-soja, brocoli sauté', 20),
  ('Sauté de crevettes, nouilles & légumes croquants', 15),
  ('Skyr + jambon roulé', 5),
  ('Œufs durs + galettes de riz', 12),
  ('Thon-fromage frais sur cracottes', 5),
  ('Yaourt grec, miel & noix', 5),
  ('Escalope de poulet, sauce moutarde légère & haricots verts', 25),
  ('Bowl burrito au bœuf', 25),
  ('Tacos de poisson & slaw citron vert', 20),
  ('Dip haricots-fromage blanc & crudités', 10),
  ('Fajitas de poulet, poivrons & oignons', 20),
  ('Crevettes à la diabla, riz coco-coriandre', 25),
  ('Burger maison patate douce', 30),
  ('Buffalo chicken bowl', 20),
  ('Cottage cheese « ranch » & crudités', 10),
  ('Meatloaf de dinde & purée légère', 35),
  ('Cajun shrimp & maïs poêlé', 15),
  ('Papillote de cabillaud à la provençale', 25),
  ('Tartine chèvre frais & concombre', 5),
  ('Blanquette de dinde allégée', 35),
  ('Poulet basquaise express', 25),
  ('Ricotta battue, miel & amandes façon colazione', 5),
  ('Pâtes thon-citron-roquette', 15),
  ('Caprese express au thon (ou classique)', 5),
  ('Escalope milanaise revisitée au four', 25),
  ('Boulettes de bœuf à la sauce arrabbiata', 30)
) as v(name, minutes)
where r.name = v.name;

-- Backfill category/protein tags for the 86 existing recipes. A recipe may
-- carry more than one tag (e.g. a sandwich with both chicken and bacon).
insert into public.recipe_tags (recipe_id, tag)
select r.id, v.tag
from (values
  ('Porridge avoine-banane', 'vegetarien'),
  ('Œufs brouillés et pain complet', 'oeuf'),
  ('Œufs brouillés et pain complet', 'vegetarien'),
  ('Yaourt grec, granola et fruits rouges', 'vegetarien'),
  ('Pancakes protéinés', 'oeuf'),
  ('Pancakes protéinés', 'vegetarien'),
  ('Poulet grillé, riz et brocolis', 'poulet'),
  ('Saumon, quinoa et légumes vapeur', 'poisson_fruits_de_mer'),
  ('Wrap dinde-avocat', 'dinde'),
  ('Buddha bowl pois chiches', 'vegetarien'),
  ('Steak haché, patate douce et haricots verts', 'boeuf'),
  ('Pâtes bolognaise (bœuf 5%)', 'boeuf'),
  ('Cabillaud, riz basmati et courgettes', 'poisson_fruits_de_mer'),
  ('Tofu sauté, nouilles et légumes', 'vegetarien'),
  ('Barre protéinée maison', 'vegetarien'),
  ('Pomme et beurre de cacahuète', 'vegetarien'),
  ('Fromage blanc et miel', 'vegetarien'),
  ('Muesli maison et lait d''amande', 'vegetarien'),
  ('Omelette au fromage et jambon', 'oeuf'),
  ('Omelette au fromage et jambon', 'porc'),
  ('Smoothie bowl banane-myrtille', 'vegetarien'),
  ('Toast à l''avocat et œuf poché', 'oeuf'),
  ('Toast à l''avocat et œuf poché', 'vegetarien'),
  ('Crêpes à la farine complète et miel', 'oeuf'),
  ('Crêpes à la farine complète et miel', 'vegetarien'),
  ('Bagel au saumon fumé et fromage frais', 'poisson_fruits_de_mer'),
  ('Porridge protéiné chocolat-noisette', 'vegetarien'),
  ('Gaufres maison et fruits', 'oeuf'),
  ('Gaufres maison et fruits', 'vegetarien'),
  ('Skyr et flocons d''avoine', 'vegetarien'),
  ('Sandwich œufs-bacon', 'oeuf'),
  ('Sandwich œufs-bacon', 'porc'),
  ('Salade César au poulet', 'poulet'),
  ('Riz sauté au tofu et légumes', 'vegetarien'),
  ('Poke bowl saumon-avocat', 'poisson_fruits_de_mer'),
  ('Sandwich club poulet-bacon', 'poulet'),
  ('Sandwich club poulet-bacon', 'porc'),
  ('Pâtes au thon et tomates', 'poisson_fruits_de_mer'),
  ('Curry de poulet et riz basmati', 'poulet'),
  ('Salade de lentilles et feta', 'vegetarien'),
  ('Burrito bœuf-haricots rouges', 'boeuf'),
  ('Bol de quinoa aux crevettes', 'poisson_fruits_de_mer'),
  ('Sandwich thon-crudités', 'poisson_fruits_de_mer'),
  ('Poulet rôti et pommes de terre', 'poulet'),
  ('Chili con carne et riz', 'boeuf'),
  ('Gratin de saumon et brocolis', 'poisson_fruits_de_mer'),
  ('Escalope de dinde et purée', 'dinde'),
  ('Risotto aux champignons et parmesan', 'vegetarien'),
  ('Curry de crevettes et riz', 'poisson_fruits_de_mer'),
  ('Poêlée de bœuf et légumes asiatiques', 'boeuf'),
  ('Lasagnes à la viande', 'boeuf'),
  ('Filet de poisson blanc et légumes rôtis', 'poisson_fruits_de_mer'),
  ('Chili végétarien et riz complet', 'vegetarien'),
  ('Amandes et fruits secs', 'vegetarien'),
  ('Smoothie protéiné banane', 'vegetarien'),
  ('Houmous et bâtonnets de légumes', 'vegetarien'),
  ('Yaourt et granola', 'vegetarien'),
  ('Barre de céréales maison', 'vegetarien'),
  ('Fromage cottage et fruits rouges', 'vegetarien'),
  ('Toast au beurre de cacahuète et banane', 'vegetarien'),
  ('Œuf dur et fruit', 'oeuf'),
  ('Œuf dur et fruit', 'vegetarien'),
  ('Shake protéiné chocolat', 'vegetarien'),
  ('Gnocchis poêlés, chorizo & tomates cerises', 'porc'),
  ('Tartare de saumon avocat-mangue', 'poisson_fruits_de_mer'),
  ('Crevettes ail-persil-piment, tagliatelles citronnées', 'poisson_fruits_de_mer'),
  ('Cabillaud rôti, sauce vierge & écrasé de patate douce', 'poisson_fruits_de_mer'),
  ('Bowl bœuf teriyaki express', 'boeuf'),
  ('Salade thaï poulet-cacahuète', 'poulet'),
  ('Saumon laqué miso-soja, brocoli sauté', 'poisson_fruits_de_mer'),
  ('Sauté de crevettes, nouilles & légumes croquants', 'poisson_fruits_de_mer'),
  ('Skyr + jambon roulé', 'dinde'),
  ('Œufs durs + galettes de riz', 'oeuf'),
  ('Œufs durs + galettes de riz', 'vegetarien'),
  ('Thon-fromage frais sur cracottes', 'poisson_fruits_de_mer'),
  ('Yaourt grec, miel & noix', 'vegetarien'),
  ('Escalope de poulet, sauce moutarde légère & haricots verts', 'poulet'),
  ('Bowl burrito au bœuf', 'boeuf'),
  ('Tacos de poisson & slaw citron vert', 'poisson_fruits_de_mer'),
  ('Dip haricots-fromage blanc & crudités', 'vegetarien'),
  ('Fajitas de poulet, poivrons & oignons', 'poulet'),
  ('Crevettes à la diabla, riz coco-coriandre', 'poisson_fruits_de_mer'),
  ('Burger maison patate douce', 'boeuf'),
  ('Buffalo chicken bowl', 'poulet'),
  ('Cottage cheese « ranch » & crudités', 'vegetarien'),
  ('Meatloaf de dinde & purée légère', 'dinde'),
  ('Cajun shrimp & maïs poêlé', 'poisson_fruits_de_mer'),
  ('Papillote de cabillaud à la provençale', 'poisson_fruits_de_mer'),
  ('Tartine chèvre frais & concombre', 'vegetarien'),
  ('Blanquette de dinde allégée', 'dinde'),
  ('Poulet basquaise express', 'poulet'),
  ('Ricotta battue, miel & amandes façon colazione', 'vegetarien'),
  ('Pâtes thon-citron-roquette', 'poisson_fruits_de_mer'),
  ('Caprese express au thon (ou classique)', 'poisson_fruits_de_mer'),
  ('Escalope milanaise revisitée au four', 'poulet'),
  ('Boulettes de bœuf à la sauce arrabbiata', 'boeuf')
) as v(name, tag)
join public.recipes r on r.name = v.name;
